### ISSUE TITLE
Using cli to fetch pages

### ISSUE THREAD

**Issue by lfen21** [gravitee-io/graviteeio-cli#143]
Hi

We are trying to use gravitee-cli to fetch pages and we have an error everytime

[root~]# gio apim pages fetch
Traceback (most recent call last):
  File "/usr/local/bin/gio", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
TypeError: fetch() got an unexpected keyword argument 'page_id'

**Comment by lfen21** [comment]
Same error with python3.8

**Comment by GGui** [comment]
Hi, I'm sorry, I no longer maintain this project. I would like to start a new project and take some part of this CLI.
Can you tell me what features you used the most? What feature is missing for you and would like to have in CLI?

Regards,
Guillaume
